rails-full-ru/caching/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope module: :web do
    root 'home#index'

    resources :articles
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

rails-full-ru/caching/app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  # BEGIN
  def last_reading_date
    Rails.cache.fetch("#{cache_key_with_version}/cached_last_reading_date", expires_in: 12.hours) do
      DateTime.now
    end
  end
  # END
end

rails-full-ru/caching/app/controllers/web/articles_controller.rb
# frozen_string_literal: true

module Web
  class ArticlesController < Web::ApplicationController
    # BEGIN
    caches_action :show
    # END

    def index
      @articles = Article.all
    end

    # BEGIN
    def show
      @article = Article.find params[:id]
    end
    # END
  end
end

rails-full-ru/caching/app/views/layouts/web/shared/_nav.html.slim
.container.mb-2
  .d-flex.flex-wrap.align-items-center.py-2.border-bottom
    .navbar.navbar-expand-md.navbar-light.me-auto
      = link_to root_path, class: 'navbar-brand me-md-4' do
        = image_tag asset_pack_path('media/images/logo.png'), width: 30, alt: t('.hexlet_logo')

      #navbarToggler.collapse.navbar-collapse
        ul.nav.nav-pills.flex-grow-1.navbar-nav.me-auto
          li.nav-item.me-2
            = link_to t('.home'), root_path, class: 'nav-link link-dark'
          li.nav-item.me-2
            = link_to t('.articles'), articles_path, class: 'nav-link link-dark'

rails-full-ru/caching/app/views/web/articles/_article.html.slim
.col.mb-3
  .card.h-100
    .card-body
      h5.card-title
        = link_to article.title, article_path(article.id)
      h6.card-subtitle.mb-2.text-muted
        = l article.published_at, format: :short
      .card-text.mb-2
        = article.summary

        .small.text-muted
          = l article.last_reading_date, format: :short

rails-full-ru/caching/app/views/web/articles/index.html.slim
= content_for :title do
  = t('.articles')

.row.row-cols-3
  - @articles.each do |article|
    / BEGIN
    - cache article do
      = render article
    / END

rails-full-ru/caching/app/views/web/articles/show.html.slim
= content_for :title do
  = @article.title

.row.row-cols-3
  = @article.body

rails-full-ru/caching/app/views/web/home/index.html.slim
- content_for :title do
  = t('.title')