rails-full-ru/jobs/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope module: :web do
    root 'home#index'

    resources :repositories, only: %i[index show new create update destroy] do
      collection do
        patch :update_repos
      end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

rails-full-ru/jobs/app/models/repository.rb
# frozen_string_literal: true

class Repository < ApplicationRecord
  validates :link, presence: true, uniqueness: true

  # BEGIN
  include AASM

  aasm do
    state :created, initial: true
    state :fetching, :fetched, :failed

    event :fetch do
      transitions from: %i[created fetched failed], to: :fetching
    end

    event :complete_fetch do
      transitions from: :fetching, to: :fetched
    end

    event :fetch_failed do
      transitions from: :fetching, to: :failed
    end
  end
  # END
end

rails-full-ru/jobs/app/controllers/web/repositories_controller.rb
# frozen_string_literal: true

module Web
  class RepositoriesController < Web::ApplicationController
    def index
      @repositories = Repository.all
    end

    def new
      @repository = Repository.new
    end

    def show
      @repository = Repository.find params[:id]
    end

    def create
      # BEGIN
      @repository = Repository.new(permitted_params)

      if @repository.save
        RepositoryLoaderJob.perform_later @repository
        redirect_to @repository, notice: 'Repository was successfully created'
      else
        render :new, status: :unprocessable_entity
      end
      # END
    end

    def update
      # BEGIN
      @repository = Repository.find params[:id]

      RepositoryLoaderJob.perform_later @repository
      redirect_to repositories_path
      # END
    end

    def update_repos
      # BEGIN
      Repository.all.each do |repository|
        RepositoryLoaderJob.perform_later repository
      end

      redirect_to repositories_path
      # END
    end

    def destroy
      @repository = Repository.find params[:id]

      if @repository.destroy
        redirect_to repositories_path, notice: t('success')
      else
        redirect_to repositories_path, notice: t('fail')
      end
    end

    private

    def permitted_params
      params.require(:repository).permit(:link)
    end
  end
end

rails-full-ru/jobs/app/views/layouts/web/application.html.slim
doctype html
html.h-100
  head
    title = t('.title')
    == csrf_meta_tags
    == csp_meta_tag
    meta name="keywords" content="template language"
    meta name="author" content='author'
    meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"
    = stylesheet_pack_tag 'application', media: 'all'
    = javascript_pack_tag 'application'

  body.d-flex.flex-column.h-100

    = render 'layouts/web/shared/nav'

    = render 'layouts/web/shared/flash'

    main
      .mt-4.mb-5.pb-5
        .container
          .p-4.align-items-center.border.shadow.bg-white.rounded-3
            .mb-4
              h2 = yield :title

            == yield

    footer.bg-dark.text-light.mt-auto
      .container-xl
        .row.py-2
          = t('.hexlet_title', year: Time.current.year)

rails-full-ru/jobs/app/views/layouts/web/shared/_nav.html.slim
.container.mb-2
  .d-flex.flex-wrap.align-items-center.py-2.border-bottom
    .navbar.navbar-expand-md.navbar-light.me-auto
      = link_to root_path, class: 'navbar-brand me-md-4' do
        = image_tag asset_pack_path('media/images/logo.png'), width: 30, alt: t('.hexlet_logo')

      #navbarToggler.collapse.navbar-collapse
        ul.nav.nav-pills.flex-grow-1.navbar-nav.me-auto
          li.nav-item.me-2
            = link_to t('.home'), root_path, class: 'nav-link link-dark'
          li.nav-item.me-2
            = link_to t('.repositories'), repositories_path, class: 'nav-link link-dark'

rails-full-ru/jobs/app/views/web/repositories/_form.html.slim
= simple_form_for(repository) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  = f.input :link

  = f.button :submit, class: 'btn btn-success mt-4 btn-block'

rails-full-ru/jobs/app/views/web/repositories/index.html.slim
- content_for :title do
  = t('.repositories')

.mb-3 = link_to t('.update_repos'), update_repos_repositories_path, method: :patch, class: 'btn btn-primary'

table.table.table-striped.table-hover.mb-5
  thead
    tr
      th{ scope = 'col' } #
      th{ scope = 'col' } = t('.link')
      th{ scope = 'col' } = t('.owner_name')
      th{ scope = 'col' } = t('.repo_name')
      th{ scope = 'col' } = t('.state')
      th{ scope = 'col' } = t('.default_branch')
      th{ scope = 'col' } = t('.watchers_count')
      th{ scope = 'col' } = t('.language')
      th{ scope = 'col' } = t('.repo_created_at')
      th{ scope = 'col' } = t('.repo_updated_at')
      th

  tbody
    - @repositories.each_with_index do |repository, i|
      tr
        th{ scope = 'row' } = i + 1
        td = repository.link
        td = repository.owner_name
        td = repository.repo_name
        td = repository.aasm.human_state
        td = repository.default_branch
        td = repository.watchers_count
        td = repository.language
        td = repository.repo_created_at
        td = repository.repo_updated_at
        td
          ul.list-group.border-0.bg-transparent
          li.list-group-item.border-0.bg-transparent
            = link_to t('show'), repository_path(repository), class: 'me-2'
          li.list-group-item.border-0.bg-transparent
            = link_to t('update'), repository_path(repository), method: :patch, class: 'me-2'
          li.list-group-item.border-0.bg-transparent
            = link_to t('destroy'), repository, data: { confirm: t('destroy_confirmation') }, method: :delete, class: 'text-danger'

= link_to t('.new_repository'), new_repository_path, class: 'btn btn-primary'

rails-full-ru/jobs/app/views/web/repositories/new.html.slim
- content_for :title do
  = t('.new_repository')

== render 'form', repository: @repository

hr

= link_to t('back'), :back, class: 'btn btn-outline-primary'

rails-full-ru/jobs/app/views/web/repositories/show.html.slim
- content_for :title do
  = @repository.link

p
  strong.me-2 = t('.repo_name')
  = @repository.repo_name
p
  strong.me-2 = t('.owner_name')
  = @repository.owner_name
p
  strong.me-2 = t('.description')
  = @repository.description
p
  strong.me-2 = t('.default_branch')
  = @repository.default_branch
p
  strong.me-2 = t('.watchers_count')
  = @repository.watchers_count
p
  strong.me-2 = t('.language')
  = @repository.language
p
  strong.me-2 = t('.repo_created_at')
  - if @repository.repo_created_at
    = l(@repository.repo_created_at, format: :long)
p
  strong.me-2 = t('.repo_updated_at')
  - if @repository.repo_updated_at
    = l(@repository.repo_updated_at, format: :long)

hr

.d-flex
  = link_to t('show'), @repository, class: 'btn btn-outline-primary me-2'
  = link_to t('back'), :back, class: 'btn btn-outline-primary'